### ISSUE TITLE
Is this being maintained?

### ISSUE THREAD

**Issue by Folcon** [promesante/hn-clj-pedestal-re-frame#2]
Firstly, thanks for writing this, it's been useful to have an example of using this and fundamentally good examples are hard to come by =)...

I cloned this locally a few days ago and after fixing the listed issues, most functionality doesn't appear to function?
I can't login, create new users or post links. I've not dug in yet to work out what the issues are.

I've created [a PR with my changes so far](https://github.com/promesante/hn-clj-pedestal-re-frame/pull/1), so hopefully that will help with debugging it.

I'm continuously getting disconnection errors, so I'm not certain if that's the reason this is happening?

```clojure
13:55:39.792 ERROR com.walmartlabs.lacinia.pedestal.subscriptions - {:event :com.walmartlabs.lacinia.pedestal.subscriptions/error, :line 499}
java.io.EOFException: Disconnected
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.disconnect(AbstractWebSocketConnection.java:323)
	at org.eclipse.jetty.websocket.common.io.DisconnectCallback.failed(DisconnectCallback.java:36)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.close(AbstractWebSocketConnection.java:200)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.remoteClose(AbstractWebSocketConnection.java:279)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:109)
	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:319)
	at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.nextIncomingFrame(AbstractExtension.java:147)
	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:112)
	at org.eclipse.jetty.websocket.common.extensions.compress.PerMessageDeflateExtension.incomingFrame(PerMessageDeflateExtension.java:71)
	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:201)
	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:226)
	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:255)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:581)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:434)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.base/java.lang.Thread.run(Thread.java:830)
```

Additionally [weavejester's reagi](https://github.com/weavejester/reagi) has been forked according to [here](https://github.com/weavejester/reagi/issues/11) to [chourave's reagi](https://github.com/chourave/reagi/tree/release-0.11.0). It doesn't help that that version doesn't appear to be up on clojars... [I've requested for that to be the case](https://github.com/chourave/reagi/issues/53).

**Comment by promesante** [comment]
hi Folcon, I am very sorry but, I don't plan to go on with this project, at least in the middle term.

Please fell free to clone it, and implement there the fixes corresponding to the PR.

And please let me know then, so that I include a link to that cloned repo at the very top of this repo's README, forwarding potentially interested people.

Thanks.

**Comment by promesante** [comment]
hi Folcon,

I've taken a look at your PR, and seems great.

Actually, I haven't taken into account this project in my middle term plans due to how clunky it got. So, I initially decided to base in REST the MVP I am starting up right now, rather than GraphQL.

However, thanks to your PR, I might review that decision.

So, please, give me some days to have the PR reviewed.

Thank you very much.

**Comment by Folcon** [comment]
@promesante No problem, there are still a few things I didn't sort out, the main one of which is sessions, basically I haven't worked out a good way of getting login over websockets to set session data.

The fundamental problem is that `lacinia-pedestal` doesn't appear to run its interceptors on websocket connections, so you can't get access to session data, as that's how you're supposed to manipulate the session.

One approach I've been thinking about is you can get `re-graph` to not use the websocket by setting:
```clojure
(re-graph/init {:ws-url nil})
```
Then once a login has occurred, you can re-init the connection with the websocket. If you're doing this though you still need to figure out how to get access to the session state within the websocket context.

Alternatively you can use multiple connections and keep the `:service-http` for stuff behind a login, like vote/submit:
```clojure
(re-graph/init :service-ws   {:ws-url "wss://localhost/graphql-ws"})
(re-graph/init :service-http {:ws-url nil})
```

I think the multiple connections might be a better approach, but I don't have any time atm to test this.
